config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get '/dang_nhap' => 'sessions#new', as: :sign_in

  get '/dang_ky' => 'registrations#new', as: :sign_up
  get '/dang_ky/:account_type' => 'registrations#new'

  get '/gui_yeu_cau' => 'jobs#new', as: :new_request
  resources :jobs, only: [:index, :new, :edit]

  get 'home/index'

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  respond_to :html

  before_action :set_locale

  include AuthenticationMethods

  before_action :init_variables

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  # def default_url_options
  #   { locale: I18n.locale }
  # end

  private

  # def extract_locale_from_accept_language_header
  #   request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  # end

  def init_variables
    # p current_user
  end
end

app/controllers/concerns/authentication_methods.rb
# frozen_string_literal: true
module AuthenticationMethods
  extend ActiveSupport::Concern

  included do
    attr_accessor :current_user
    before_action :init_user
  end

  private

  def init_user
    @current_user = JSON.parse(cookies['current_user']) if cookies['current_user']
  end

  def user_signed_in?
    @current_user ? true : false
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true
class JobsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true
class RegistrationsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true
class SessionsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/helpers/authentication_helper.rb
# frozen_string_literal: true
module AuthenticationHelper
  def current_user
    @current_user
  end

  def user_signed_in?
    @current_user ? true : false
  end
end

app/helpers/menu_helper.rb
# frozen_string_literal: true
module MenuHelper
  def home_menu_class
    current_page?(home_index_path) || current_page?(root_path) ? 'item active' : 'item'
  end

  def jobs_menu_class
    current_page?(jobs_path) ? 'item active' : 'item'
  end
end

app/helpers/react_helper.rb
# frozen_string_literal: true
module ReactHelper
  def view_params
    {
      requestParams: params,
      images: {
        logo: image_path('logo.png')
      }
    }
  end
end

app/views/home/index.html.erb
<div class="ui vertical masthead center aligned segment">
  <div class="ui container">
    <h1 class="ui header">Bạn cần tìm <span class="highlight">Nhà Thầu Xây Dựng</span>?</h1>

    <%= link_to new_request_path, class: 'ui massive yellow request button' do %>
      <i class="send icon"></i>
      <%= 'GỬI YÊU CẦU' %>
    <% end %>

    <p class="sub header">
      Đội ngũ Kiến Trúc Sư và Nhà Thầu uy tín chuyên nghiệp, tư vấn thiết kế, báo giá xây dựng miễn phí.
    </p>
  </div>
</div>


<div class="ui vertical very padded center aligned grey segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="sixteen wide column">
        <h1 class="ui section header">Các dịch vụ chính</h1>
      </div>
    </div>

    <div class="horizontal content content-01 row">
      <div class="eleven wide left column">
        <div class="ui vertical compact box segment">
          <h2 class="ui header">Thiết Kế Kiến Trúc</h2>
          <p>Thiết kế kiến trúc với phong cách hiện đại không gian mở hoà hợp giữa kiến trúc và thiên nhiên.</p>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
      <div class="five wide right column">
        <%= image_tag 'icons/icon-pencil-ruler.png' %>
        <br />
        <br />
        <p>Thiết kế kiến trúc<br />Thiết kế 3d nội thất<br />Hồ sơ dự toán công trình</p>
        <br />
        <br />
        <%= link_to '> Báo giá', '/', class: 'ui yellow text' %>
      </div>
    </div>

    <div class="horizontal content content-02 row">
      <div class="eleven wide left column">
        <div class="ui vertical compact box segment">
          <h2 class="ui header">Thi Công Xây Dựng</h2>
          <p>Nhà thầu thi công xây dựng uy tín chuyên nghiệp, bảo đảm chất lượng công trình.</p>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
      <div class="five wide right column">
        <p>Vật tư chính phần thô<br />Vật tư chính phần hoàn thiện</p>
        <br />
        <br />
        <%= link_to '> Báo giá', '/', class: 'ui yellow text' %>
      </div>
    </div>

    <div class="horizontal content content-03 row">
      <div class="eleven wide left column">
        <div class="ui vertical compact box segment">
          <h2 class="ui header">Hoàn Thiện Nội Thất</h2>
          <p>Hoàn thiện nội thất căn hộ, nhà phố, biệt thự cao cấp từ các thương hiệu nổi tiếng.</p>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
      <div class="five wide right column">
        <%= image_tag 'icons/icon-sofa.png' %>
        <br />
        <br />
        <p>
          Phần khung thô<br />Phần hoàn thiện và trang trí nội thất<br />Hệ thống điện<br />Hệ thống cấp - thoát nước
        </p>
        <br />
        <br />
        <%= link_to '> Báo giá', '/', class: 'ui yellow text' %>
      </div>
    </div>

  </div>
</div>


<div class="ui vertical very padded center aligned grey segment">
  <div class="ui grid container">
    <div class="row">
      <div class="sixteen wide column">
        <h1 class="ui section header">Các dịch vụ khác</h1>
      </div>
    </div>
  </div>

  <div class="ui stackable three column grid container">
    <div class="column">
      <div class="service service-01">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Sơn Nội Ngoại Thất<br /><br /></h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="service service-02">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Sàn Gỗ, Thảm Sàn,<br />Lát Gạch</h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="service service-03">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Camera Quan Sát<br /><br /></h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="service service-04">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Cảnh Quan, Cây Xanh<br /><br /></h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="service service-05">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Dịch Vụ Chống Thấm<br /><br /></h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="service service-06">
        <div class="ui vertical top segment"></div>
        <div class="ui vertical bottom segment">
          <h2 class="ui header">Hồ Bơi<br /><br /></h2>
          <a href="/" class="ui yellow button">GỬI YÊU CẦU</a>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical very padded center aligned segment">
  <div class="ui stackable grid container">
    <div class="row">
      <div class="sixteen wide column">
        <h1 class="ui section header">Chúng tôi là ai?</h1>
      </div>
    </div>

    <div class="row">
      <div class="eleven wide column">
        <iframe width="100%" height="430" src="https://www.youtube.com/embed/IVRoDeNY3Gg" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="five wide column">
        <div class="ui vertical about-us segment">
          <h2 class="ui header">
            NHATHAUVANG.COM là nơi kết nối giữa Chủ nhà và Nhà Thầu
          </h2>

          <p>Chúng tôi hiểu được nhu cầu của bạn và mang lại cho bạn đối tác uy tín và chất lượng.</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical segment">
 <div class="ui stackable three column grid container">
   <div class="row">
     <div class="column">
       <div class="ui center aligned padded info segment">
         <h3 class="ui header">Gửi yêu cầu miễn phí</h3>
         <p><%= image_tag 'icons/icon-email.png' %></p>
         <p>Yêu cầu càng chi tiết càng giúp nhà thầu lên phương án tốt nhất cho bạn</p>
       </div>
     </div>
     <div class="column">
       <div class="ui center aligned padded info segment">
         <h3 class="ui header">Liên hệ ngay trong 24h</h3>
         <p><%= image_tag 'icons/icon-phone-24h.png' %></p>
         <p>Lựa chọn nhà thầu thông qua hồ sơ năng lực và đánh giá từ khách hàng khác</p>
       </div>
     </div>
     <div class="column">
       <div class="ui center aligned padded info segment">
         <h3 class="ui header">Tiến hành nhanh chóng</h3>
         <p><%= image_tag 'icons/icon-rocket.png' %></p>
         <p>Giám sát chặt chẽ công việc của bạn và đánh giá khi dự án hoàn thành</p>
       </div>
     </div>
   </div>

   <div class="row">
     <div class="column">
       <div class="ui center aligned very padded info basic grey segment">
         <p><%= image_tag 'icons/icon-phone-circle.png' %></p>
         <p class="highlight">0985 393 868</p>
       </div>
     </div>
     <div class="column">
       <div class="ui center aligned very padded info basic grey segment">
         <p><%= image_tag 'icons/icon-facebook-circle.png' %></p>
         <p><a href="www.facebook.com/nhathauvangvietnam/" target="_blank">www.facebook.com/nhathauvangvietnam/</a></p>
       </div>
     </div>
     <div class="column">
       <div class="ui center aligned very padded info basic grey segment">
         <p><%= image_tag 'icons/icon-email-circle.png' %></p>
         <p><a href="mailto:info@nhathauvang.com">info@nhathauvang.com</a></p>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/jobs/index.html.erb
<div class="ui vertical masthead segment">
  <div class="ui container">
  </div>
</div>

app/views/jobs/new.html.erb
<%= react_component 'NewJobView', {}, { prerender: true } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Nhà Thầu Vàng</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <script type="application/javascript">
    window.API_URL = '<%= ENV['API_URL'] %>';
    window.APP_ENV = '<%= ENV['RAILS_ENV'] %>';
    window.APP_HOST = '<%= request.domain %>';
  </script>

  <%= javascript_include_tag 'application' %>
  <!-- <%= javascript_include_tag 'server_prerender' %> -->
</head>
<body>

<%= render 'navigation/menu' %>

<div class="pusher">
  <%= render 'navigation/main_topnav' %>

  <div class="<%= "#{params[:controller]} #{params[:action]}" %>">
    <%= yield %>
  </div>
</div>

<%= render 'shared/footer' %>

</body>

</html>

app/views/navigation/_main_topnav.html.erb
<div class="ui top-nav large menu">
  <div class="ui container">
    <a class="toc item">
      <i class="sidebar icon"></i>
    </a>
    <%= link_to root_path, class: 'logo' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <%= link_to t('navigation.topnav.blog'), root_path, class: 'item' %>
    <%= link_to t('navigation.topnav.project'), root_path, class: 'item' %>
    <div class="right menu">
      <div class="item">
        <%= link_to new_request_path, class: 'ui basic yellow button' do %>
          <i class="send icon"></i>
          <%= t('navigation.topnav.new_request') %>
        <% end %>
      </div>
      <%= link_to t('navigation.topnav.log_in'), sign_in_path, class: 'item' %>
      <%= link_to t('navigation.topnav.sign_up'), sign_up_path, class: 'item' %>
    </div>
  </div>
</div>

app/views/navigation/_menu.html.erb
<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <%= link_to root_path, class: 'logo' do %>
      <%= image_tag 'logo-ntv.png' %>
    <% end %>
    <%= link_to t('navigation.topnav.blog'), root_path, class: 'item' %>
    <%= link_to t('navigation.topnav.project'), root_path, class: 'item' %>

    <div class="right menu">
      <div class="item">
        <%= link_to new_job_path, class: 'ui basic yellow button' do %>
          <i class="send icon"></i>
          <%= t('navigation.topnav.new_request') %>
        <% end %>
      </div>
      <%= link_to t('navigation.topnav.log_in'), root_path, class: 'item' %>
      <%= link_to t('navigation.topnav.sign_up'), root_path, class: 'item' %>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical sidebar menu">
  <%= link_to root_path, class: 'logo' do %>
    <%= image_tag 'logo-ntv.png' %>
  <% end %>
  <%= link_to t('navigation.topnav.blog'), root_path, class: 'item' %>
  <%= link_to t('navigation.topnav.project'), jobs_path, class: 'item' %>
  <%= link_to t('navigation.topnav.new_request'), new_job_path, class: 'item' %>
  <%= link_to t('navigation.topnav.log_in'), root_path, class: 'item' %>
  <%= link_to t('navigation.topnav.sign_up'), root_path, class: 'item' %>
</div>

app/views/shared/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui stackable inverted equal height grid">
      <div class="five wide column">
        <%= image_tag 'logo-ntv-sm.png' %>
        <div class="ui inverted link list">
          <p>
            CTY CỔ PHẦN CÔNG NGHỆ THIÊN MINH<br />
            68 Nguyễn Huệ, Quận 1, TpHCM<br />
            Điện thoại: (08) 6266 6868<br />
            Email: <a href="mailto:info@nhathauvang.com">info@nhathauvang.com</a>
          </p>
        </div>
      </div>
      <div class="eleven wide column">
        <div class="ui stackable equal height three column grid">
          <div class="column">
            <h4 class="ui inverted header">NHATHAUVANG.COM</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Giới thiệu</a>
              <a href="#" class="item">Liên hệ</a>
              <a href="#" class="item">Điều khoản sử dụng</a>
              <a href="#" class="item">Quy chế hoạt động</a>
              <a href="#" class="item">Cơ chế giải quyết tranh chấp</a>
            </div>
          </div>

          <div class="column">
            <h4 class="ui inverted header">Chủ Nhà</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Gửi yêu cầu</a>
              <a href="#" class="item">Cách thức hoạt động</a>
              <a href="#" class="item">Hỏi đáp</a>
            </div>
          </div>

          <div class="column">
            <h4 class="ui inverted header">Nhà Thầu</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Đăng ký thành viên</a>
              <a href="#" class="item">Cách thức hoạt động</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>